### ISSUE TITLE
requirement error

### ISSUE THREAD

**Issue by mrhelixx** [saeedehj/mood-audio-classification#1]
requirement file is not labeled right.. (no s or .txt)

corrected path?
mood-audio-classification\code\models\requirements.txt
easy fix though.
ty

**Comment by saeedehj** [comment]
Thanks for your message,  I fixed the issue.

**Comment by Superhu003** [comment]
hi，
Did you encounter any missing files while running it?
file is /mood-audio-classification-main/data/vggish_final.npz.

**Comment by Superhu003** [comment]
@mrhelixx
